services:
  app:
    build: .
    container_name: php_imagine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
